#!/bin/sh

### BEGIN INIT INFO
# Provides:          mage-server1
# Required-Start:    $local_fs $all apache2
# Required-Stop:
# Default-Start:     2
# Default-Stop:
# Short-Description: MTG Server
### END INIT INFO

case "$1" in
    start)
    base=/usr/games/mage-server1
    cd $base
    /usr/bin/cpulimit -l 50 -- \
        /usr/bin/java \
        -Xms1024M -Xmx2048M -XX:MaxPermSize=512m \
        -Djava.security.policy=./config/security.policy \
        -Djava.util.logging.config.file=./config/logging.config \
        -Dlog4j.configuration=file:./config/log4j.properties \
        -jar $base/lib/mage-server-1.3.0.jar \
        -adminPassword=[yourAdminPW] >/dev/null 2>/dev/null &
    ;;
    stop)
        pkill -f "/usr/bin/java.*"${base}"/lib/mage-server-"
     ;;
    restart)
    $0 stop
    sleep 1
    $0 start
    ;;
esac